export interface RestaurantMessage {
  id: number
  restaurant_id: number
  author: string
  content: string
  created_at: string
}

// Mirrors the `restaurants` table in Supabase.
export interface Restaurant {
  id: number
  name: string
  city: string
  address: string
  cuisine_type: string
  rating: number
  notes: string
  avg_cost: number | null
  visited_date: string
  created_at: string
  poi_id: string | null
  message_count: number
  messages?: RestaurantMessage[]   // 懒加载，打开留言板时才填充
}

// `id` and `created_at` are generated by database.
export type RestaurantInsert = Omit<Restaurant, 'id' | 'created_at' | 'messages' | 'message_count'>
